---
- name: Install aptitude using apt
  apt:
    name: 'aptitude'
    state: 'latest'
    update_cache: 'yes'
    force_apt_get: 'yes'

- name: 'Install prerequisites'
  apt:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
      - 'gnupg2'
    state: 'present'
    update_cache: yes

- name: 'Add the docker apt signing key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'

- name: 'Add the official docker repo'
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable'
    state: 'present'

- name: 'Install docker'
  apt:
    name:
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'
      - 'docker-compose'
    state: 'present'
    update_cache: yes

- name: 'Create the /etc/docker directory'
  file:
    path: '/etc/docker'
    state: 'directory'
    mode: '0700'

- name: 'Add any additional docker startup options via the daemon.json config file'
  copy:
    content: "{{ docker_additional_service_opts }}"
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: 'docker-restart-service'

- name: 'Start the docker service'
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'

- name: 'Add current user to docker group'
  become: yes
  user:
    name: "{{ docker_user }}"
    groups: 'docker'
    append: yes

- name: 'Check that the docker.pid exists'
  stat:
    path: /run/docker.pid
  register: stat_result
  failed_when: stat_result.stat.exists != true

- name: 'Result of check docker.pid'
  debug:
    msg: 'Docker started'
  when: stat_result.stat.exists

- name: 'Install python3-pip'
  apt:
    name: 'python3-pip'
    state: 'present'

- name: 'Install docker-py'
  pip:
    name: 'docker-py'
    state: 'present'
