---
- name: 'Install apt-transport-https'
  apt:
    name: 'apt-transport-https'

- name: 'Add the docker apt signing key'
  apt_key:
    keyserver: 'pool.sks-keyservers.net'
    id: '58118E89F3A912897C070ADBF76221572C52609D'
  notify: 'docker-apt-get-update'

- name: 'Add the official docker repo'
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main'
    state: 'present'
  notify: 'docker-apt-get-update'

- meta: flush_handlers

- name: 'Install docker'
  apt:
    name: 'docker-engine'
    state: 'latest'

- name: 'Create the /etc/docker directory'
  file:
    path: '/etc/docker'
    state: 'directory'
    mode: '0700'

- name: 'Add any additional docker startup options via the daemon.json config file'
  copy:
    content: "{{ docker_additional_service_opts }}"
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: 'docker-restart-service'

- name: 'Start the docker service'
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'

- name: 'Add current user to docker group'
  become: yes
  user:
    name: "{{ docker_user }}"
    groups: 'docker'
    append: yes

- name: 'Check that the docker.pid exists'
  stat:
    path: /run/docker.pid
  register: stat_result
  failed_when: stat_result.stat.exists != true

- name: 'Result of check docker.pid'
  debug:
    msg: 'Docker started'
  when: stat_result.stat.exists

- name: 'Install python3-pip'
  apt:
    name: 'python3-pip'
    state: 'present'

- name: 'Install docker-py'
  pip:
    name: 'docker-py'
    state: 'present'

- name: 'Install docker-compose'
  pip:
    name: 'docker-compose'
    state: 'present'
